import type { BusinessSeed } from "@/features/catalog/catalog.types";

import {
  createBusinessLinks,
  createDefaultWhatsappContactDetails,
  createShoppingPlaceholderMedia
} from "./factories";

export const shoppingBusinessSeeds: BusinessSeed[] = [
  {
    id: "isola-di-lino",
    categoryId: "shopping",
    name: "Isola di Lino",
    type: "Boutique resortwear",
    shortDescription: "Caftani, lino e capi leggeri ispirati ai colori del Mediterraneo.",
    description:
      "Una boutique dedicata a resortwear, lino e tessuti freschi pensati per vivere l'isola con uno stile rilassato ma curato. Collezioni selezionate per chi cerca eleganza semplice e vacanza senza eccessi.",
    openingHours: "10:00 - 13:00 • 18:00 - 23:00",
    address: "Via Roma 5, Lampedusa",
    location: { latitude: 35.516210, longitude: 12.618140 },
    contact: createDefaultWhatsappContactDetails("393490002001", "Isola di Lino"),
    links: createBusinessLinks("isola-di-lino"),
    media: createShoppingPlaceholderMedia(1),
  },
  {
    id: "bottega-del-porto",
    categoryId: "shopping",
    name: "Bottega del Porto",
    type: "Souvenir & gift shop",
    shortDescription: "Oggetti da regalo, calamite, cartoline e idee da portare a casa.",
    description:
      "Una bottega luminosa e ordinata con una selezione di souvenir, piccoli regali e oggetti da viaggio ispirati a Lampedusa. Perfetta per chi vuole portare con se un ricordo immediato dell'isola.",
    openingHours: "09:30 - 13:00 • 17:30 - 23:30",
    address: "Lungomare Luigi Rizzo 14, Lampedusa",
    location: { latitude: 35.515640, longitude: 12.617420 },
    contact: createDefaultWhatsappContactDetails("393490002002", "Bottega del Porto"),
    links: createBusinessLinks("bottega-del-porto"),
    media: createShoppingPlaceholderMedia(2),
  },
  {
    id: "coralli-boutique",
    categoryId: "shopping",
    name: "Coralli Boutique",
    type: "Moda mare",
    shortDescription: "Beachwear, costumi e accessori in una selezione raffinata.",
    description:
      "Uno spazio dedicato alla moda mare con costumi, copricostume e accessori curati nei dettagli. Ideale per chi vuole completare il proprio guardaroba da vacanza con linee leggere e palette mediterranee.",
    openingHours: "10:00 - 13:00 • 18:30 - 23:00",
    address: "Via Vittorio Emanuele 21, Lampedusa",
    location: { latitude: 35.513980, longitude: 12.620310 },
    contact: createDefaultWhatsappContactDetails("393490002003", "Coralli Boutique"),
    links: createBusinessLinks("coralli-boutique"),
    media: createShoppingPlaceholderMedia(3),
  },
  {
    id: "pelagie-concept-store",
    categoryId: "shopping",
    name: "Pelagie Concept Store",
    type: "Lifestyle store",
    shortDescription: "Oggetti, accessori e piccole edizioni dedicate allo stile dell'isola.",
    description:
      "Un concept store che unisce lifestyle, accessori e piccoli pezzi di design con una sensibilita contemporanea. La selezione mette insieme gusto locale e un'immagine piu editoriale del Mediterraneo.",
    openingHours: "10:30 - 13:00 • 18:00 - 22:30",
    address: "Via Maccaferri 3, Lampedusa",
    location: { latitude: 35.514920, longitude: 12.614880 },
    contact: createDefaultWhatsappContactDetails("393490002004", "Pelagie Concept Store"),
    links: createBusinessLinks("pelagie-concept-store"),
    media: createShoppingPlaceholderMedia(4),
  },
  {
    id: "casa-grecale",
    categoryId: "shopping",
    name: "Casa Grecale",
    type: "Artigianato tessile",
    shortDescription: "Tessili, ricami e oggetti per la casa ispirati all'isola.",
    description:
      "Una selezione di tessili, tovaglie, ricami e dettagli per la casa che raccontano il lato piu delicato e artigianale dell'isola. Perfetta per chi cerca un ricordo utile e ben fatto.",
    openingHours: "09:30 - 13:00 • 18:00 - 22:00",
    address: "Via Grecale 11, Lampedusa",
    location: { latitude: 35.517240, longitude: 12.621060 },
    contact: createDefaultWhatsappContactDetails("393490002005", "Casa Grecale"),
    links: createBusinessLinks("casa-grecale"),
    media: createShoppingPlaceholderMedia(5),
  },
  {
    id: "sette-venti",
    categoryId: "shopping",
    name: "Sette Venti",
    type: "Abbigliamento uomo e donna",
    shortDescription: "Capi casual, linee estive e accessori per passeggio e vacanza.",
    description:
      "Un negozio di abbigliamento con linee estive, capi facili da indossare e proposte per uomo e donna. Ideale per chi vuole acquistare qualcosa di pratico ma ben rifinito durante il soggiorno.",
    openingHours: "10:00 - 13:00 • 18:00 - 23:00",
    address: "Via Roma 32, Lampedusa",
    location: { latitude: 35.516880, longitude: 12.616730 },
    contact: createDefaultWhatsappContactDetails("393490002006", "Sette Venti"),
    links: createBusinessLinks("sette-venti"),
    media: createShoppingPlaceholderMedia(6),
  },
  {
    id: "cala-bianca-souvenir",
    categoryId: "shopping",
    name: "Cala Bianca Souvenir",
    type: "Souvenir shop",
    shortDescription: "Ricordi di viaggio, piccole stampe e idee regalo immediate.",
    description:
      "Uno spazio dedicato a souvenir, piccole stampe, oggetti da viaggio e idee regalo da acquistare con rapidita. Una tappa comoda per chi cerca un ricordo semplice ma curato.",
    openingHours: "09:30 - 13:00 • 18:30 - 23:30",
    address: "Via Roma 48, Lampedusa",
    location: { latitude: 35.514260, longitude: 12.619550 },
    contact: createDefaultWhatsappContactDetails("393490002007", "Cala Bianca Souvenir"),
    links: createBusinessLinks("cala-bianca-souvenir"),
    media: createShoppingPlaceholderMedia(1),
  },
  {
    id: "lab-mediterraneo",
    categoryId: "shopping",
    name: "Lab Mediterraneo",
    type: "Ceramiche e handmade",
    shortDescription: "Ceramiche decorative, oggetti fatti a mano e piccole serie locali.",
    description:
      "Un laboratorio-bottega con ceramiche, oggetti handmade e piccole serie ispirate ai colori marini. Pensato per chi ama un acquisto piu artigianale e meno turistico.",
    openingHours: "10:30 - 13:00 • 18:00 - 22:30",
    address: "Via Cameroni 8, Lampedusa",
    location: { latitude: 35.513440, longitude: 12.615970 },
    contact: createDefaultWhatsappContactDetails("393490002008", "Lab Mediterraneo"),
    links: createBusinessLinks("lab-mediterraneo"),
    media: createShoppingPlaceholderMedia(2),
  },
  {
    id: "sabbia-chiara-kids",
    categoryId: "shopping",
    name: "Sabbia Chiara Kids",
    type: "Beachwear bambini",
    shortDescription: "Abbigliamento mare e accessori pensati per i piu piccoli.",
    description:
      "Un punto vendita dedicato ai piu piccoli con beachwear, cappelli, sandali e accessori utili per il mare. Colori chiari, materiali leggeri e una selezione pratica per famiglie in vacanza.",
    openingHours: "10:00 - 13:00 • 18:00 - 22:00",
    address: "Via Cala Croce 6, Lampedusa",
    location: { latitude: 35.511980, longitude: 12.608560 },
    contact: createDefaultWhatsappContactDetails("393490002009", "Sabbia Chiara Kids"),
    links: createBusinessLinks("sabbia-chiara-kids"),
    media: createShoppingPlaceholderMedia(3),
  },
  {
    id: "via-roma-boutique",
    categoryId: "shopping",
    name: "Via Roma Boutique",
    type: "Fashion boutique",
    shortDescription: "Abiti, completi leggeri e accessori per il centro e la sera.",
    description:
      "Una boutique dal taglio piu cittadino con proposte moda per passeggio, aperitivo e serata. Una selezione ordinata di capi leggeri e accessori facili da indossare anche in vacanza.",
    openingHours: "10:30 - 13:00 • 18:30 - 23:00",
    address: "Via Roma 61, Lampedusa",
    location: { latitude: 35.515180, longitude: 12.617950 },
    contact: createDefaultWhatsappContactDetails("393490002010", "Via Roma Boutique"),
    links: createBusinessLinks("via-roma-boutique"),
    media: createShoppingPlaceholderMedia(4),
  },
  {
    id: "blu-cobalto-atelier",
    categoryId: "shopping",
    name: "Blu Cobalto Atelier",
    type: "Gioielli artigianali",
    shortDescription: "Piccoli gioielli, dettagli smaltati e lavorazioni ispirate al mare.",
    description:
      "Atelier dedicato a gioielli, piccoli accessori e dettagli smaltati dalle tonalita marine. Perfetto per chi cerca un acquisto piu personale e un ricordo meno convenzionale.",
    openingHours: "11:00 - 13:00 • 18:30 - 22:30",
    address: "Via Grecale 29, Lampedusa",
    location: { latitude: 35.517860, longitude: 12.620880 },
    contact: createDefaultWhatsappContactDetails("393490002011", "Blu Cobalto Atelier"),
    links: createBusinessLinks("blu-cobalto-atelier"),
    media: createShoppingPlaceholderMedia(5),
  },
  {
    id: "porto-piccolo-market",
    categoryId: "shopping",
    name: "Porto Piccolo Market",
    type: "Accessori & beach essentials",
    shortDescription: "Teli, borse mare, accessori utili e piccoli acquisti dell'ultimo minuto.",
    description:
      "Un punto vendita pratico per accessori mare, teli, borse, cappelli e piccoli articoli da usare subito. Pensato per chi vuole completare il necessario senza perdere tempo.",
    openingHours: "09:00 - 13:00 • 17:30 - 23:30",
    address: "Area Porto, Lampedusa",
    location: { latitude: 35.514730, longitude: 12.613940 },
    contact: createDefaultWhatsappContactDetails("393490002012", "Porto Piccolo Market"),
    links: createBusinessLinks("porto-piccolo-market"),
    media: createShoppingPlaceholderMedia(6),
  },
  {
    id: "pozzolana-store",
    categoryId: "shopping",
    name: "Pozzolana Store",
    type: "Home decor",
    shortDescription: "Oggetti decorativi, profumi ambiente e dettagli per la casa.",
    description:
      "Uno store dedicato a oggetti decorativi, fragranze e dettagli per la casa con un gusto morbido e mediterraneo. Una scelta ideale per chi cerca un acquisto piu raffinato.",
    openingHours: "10:00 - 13:00 • 18:00 - 22:30",
    address: "Via Pozzo Monaco 4, Lampedusa",
    location: { latitude: 35.860820, longitude: 12.862540 },
    contact: createDefaultWhatsappContactDetails("393490002013", "Pozzolana Store"),
    links: createBusinessLinks("pozzolana-store"),
    media: createShoppingPlaceholderMedia(1),
  },
  {
    id: "linosa-made",
    categoryId: "shopping",
    name: "Linosa Made",
    type: "Artigianato locale",
    shortDescription: "Oggetti, stampe e lavorazioni ispirate alla natura di Linosa.",
    description:
      "Una selezione di oggetti artigianali, stampe e piccole produzioni dedicate all'identita di Linosa. Ideale per chi vuole un ricordo piu autentico e legato alle Pelagie.",
    openingHours: "10:30 - 13:00 • 18:00 - 21:30",
    address: "Via Pozzolana di Ponente 9, Linosa",
    location: { latitude: 35.515960, longitude: 12.618920 },
    contact: createDefaultWhatsappContactDetails("393490002014", "Linosa Made"),
    links: createBusinessLinks("linosa-made"),
    media: createShoppingPlaceholderMedia(2),
  },
  {
    id: "isola-sunwear",
    categoryId: "shopping",
    name: "Isola Sunwear",
    type: "Occhiali e cappelli",
    shortDescription: "Accessori sole e beachwear selezionati per il clima delle isole.",
    description:
      "Occhiali, cappelli, borse leggere e accessori da sole raccolti in uno spazio semplice e ben assortito. Una fermata utile per chi cerca articoli funzionali ma con un buon taglio estetico.",
    openingHours: "10:00 - 13:00 • 18:00 - 22:30",
    address: "Via Roma 74, Lampedusa",
    location: { latitude: 35.513760, longitude: 12.615230 },
    contact: createDefaultWhatsappContactDetails("393490002015", "Isola Sunwear"),
    links: createBusinessLinks("isola-sunwear"),
    media: createShoppingPlaceholderMedia(3),
  },
  {
    id: "filo-di-sale",
    categoryId: "shopping",
    name: "Filo di Sale",
    type: "Borse e accessori",
    shortDescription: "Borse leggere, pouch e dettagli tessili per viaggio e spiaggia.",
    description:
      "Una piccola boutique di borse, pouch e accessori tessili pensati per il viaggio e la spiaggia. Materiali leggeri, colori sabbia e un'identita visiva pulita e curata.",
    openingHours: "10:30 - 13:00 • 18:30 - 22:30",
    address: "Via Cameroni 17, Lampedusa",
    location: { latitude: 35.516520, longitude: 12.619840 },
    contact: createDefaultWhatsappContactDetails("393490002016", "Filo di Sale"),
    links: createBusinessLinks("filo-di-sale"),
    media: createShoppingPlaceholderMedia(4),
  },
  {
    id: "marea-boutique",
    categoryId: "shopping",
    name: "Marea Boutique",
    type: "Abbigliamento donna",
    shortDescription: "Linee femminili, tessuti estivi e accessori per la sera.",
    description:
      "Boutique donna con una selezione estiva fatta di abiti fluidi, capi leggeri e accessori facili da abbinare. Una proposta pensata per la vacanza ma con un tocco piu ricercato.",
    openingHours: "10:00 - 13:00 • 18:30 - 23:00",
    address: "Via Roma 83, Lampedusa",
    location: { latitude: 35.514480, longitude: 12.616180 },
    contact: createDefaultWhatsappContactDetails("393490002017", "Marea Boutique"),
    links: createBusinessLinks("marea-boutique"),
    media: createShoppingPlaceholderMedia(5),
  },
  {
    id: "tramontana-shop",
    categoryId: "shopping",
    name: "Tramontana Shop",
    type: "T-shirt e souvenir",
    shortDescription: "T-shirt grafiche, felpe leggere e souvenir dal taglio contemporaneo.",
    description:
      "Uno shop dedicato a T-shirt, felpe leggere e souvenir grafici ispirati alle isole. Ideale per chi vuole un ricordo giovane, semplice e subito indossabile.",
    openingHours: "09:30 - 13:00 • 18:00 - 23:00",
    address: "Via Vittorio Emanuele 9, Lampedusa",
    location: { latitude: 35.513220, longitude: 12.621420 },
    contact: createDefaultWhatsappContactDetails("393490002018", "Tramontana Shop"),
    links: createBusinessLinks("tramontana-shop"),
    media: createShoppingPlaceholderMedia(6),
  },
  {
    id: "nasse-e-trame",
    categoryId: "shopping",
    name: "Nasse & Trame",
    type: "Tessuti e ricami",
    shortDescription: "Ricami, dettagli tessili e manufatti ispirati alla tradizione locale.",
    description:
      "Uno spazio raccolto dedicato a tessuti, ricami e manufatti che reinterpretano la tradizione isolana con gusto piu attuale. Una tappa ideale per chi ama la materia e il dettaglio.",
    openingHours: "10:30 - 13:00 • 18:00 - 22:00",
    address: "Via Grecale 42, Lampedusa",
    location: { latitude: 35.517020, longitude: 12.617110 },
    contact: createDefaultWhatsappContactDetails("393490002019", "Nasse & Trame"),
    links: createBusinessLinks("nasse-e-trame"),
    media: createShoppingPlaceholderMedia(1),
  },
  {
    id: "pelagos-wear",
    categoryId: "shopping",
    name: "Pelagos Wear",
    type: "Resort shop",
    shortDescription: "Abbigliamento vacanza, accessori e capi easywear per l'isola.",
    description:
      "Resort shop con una selezione di capi easywear, accessori e abbigliamento leggero adatto alle giornate lunghe e luminose di Lampedusa. Uno spazio ordinato e facile da leggere.",
    openingHours: "10:00 - 13:00 • 18:00 - 22:30",
    address: "Via Roma 91, Lampedusa",
    location: { latitude: 35.515310, longitude: 12.620020 },
    contact: createDefaultWhatsappContactDetails("393490002020", "Pelagos Wear"),
    links: createBusinessLinks("pelagos-wear"),
    media: createShoppingPlaceholderMedia(2),
  }
];